name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        conf:
          - BorrowRateView
          - ExpectedMarketBalances

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          submodules: recursive

      - name: Install Jq
        uses: sergeysova/jq-action@a3f0d4ff59cc1dddf023fc0b325dd75b10deec58 # v2

      - name: Run Certora Config Linter
        run: |
          file="certora/confs/${{ matrix.conf }}.conf"
          diff <(jq . "$file") "$file"

      - name: Install python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4

      - name: Install certora
        run: pip install certora-cli

      - name: Install solc (0.8.19)
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc-0.8.19

      - name: Verify ${{ matrix.conf }}
        run: certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
